name: Unit Tests

on: [push, pull_request]

env:
  PNPM_VERSION: "7.9.1"
  NODE_VERSION: "16.x"

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: "${{ matrix.os }} | Node ${{ matrix.node }}"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm i --frozen-lockfile --production false
      - run: pnpm test -- --coverage

  publish:
    if: github.event_name == 'push' && (github.ref_name == 'master' || github.ref_name == 'next')
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i --frozen-lockfile --production false
      - if: github.ref_name == 'master'
        run: pnpm publish --recursive --filter="@jmondi/*" --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - if: github.ref_name == 'next'
        run: pnpm publish --recursive --filter="@jmondi/*" --access=public --publish-branch next --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}